### ISSUE TITLE
internal error: package "encoding/json" without types was imported from "local package"

### ISSUE THREAD

**Issue by not-rusty** [BurntSushi/go-sumtype#17]
I'm not sure why I'm getting this error. I'm on go 1.18.

The same happens actually when using other packages:

`internal error: package "fmt" without types was imported from "command-line-arguments"`

**Comment by BurntSushi** [comment]
Well if it's happening using other packages too then it seems like it's not an issue with this package and probably an environment or configuration issue on your end...

**Comment by not-rusty** [comment]
Wow really quick response!
It is indeed not an issue of this package, I found out on this comment:

https://github.com/golang/go/issues/37617#issuecomment-619184447

Apparently go-sumtype "golang.org/x/tools/go/packages" version is outdated, updating it solves the issue.
